### ISSUE TITLE
本地运行怎么登录？照教程添加可信域名不成功

### ISSUE THREAD

**Issue by IceApriler** [WecomTeam/InnerAppCodeSample#13]
大佬，帮忙看看本地怎么登录然后调试？谢谢！

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/29689307/206473207-3cebd4ad-e97f-4208-8f10-cecf5d0e9cf0.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/29689307/206472671-7bff8708-ccc7-43b7-9e84-e2a38597ef45.png">

**Comment by haohao6683** [comment]
您好，我也遇到同样的问题，请问解决了吗？ @IceApriler

**Comment by haohao6683** [comment]
@meterscao @chuyueZhang

**Comment by meterscao** [comment]
所以你添加了你们自己的可信域名了吗？不会真的写的是 myapp.com:3000 吧

**Comment by meterscao** [comment]
我今天确认了下，新创建的自建应用必须走可信域名验证了，所以尽可能按照真是的可信域名进行测试吧

**Comment by haohao6683** [comment]
> 我今天确认了下，新创建的自建应用必须走可信域名验证了，所以尽可能按照真是的可信域名进行测试吧

好的明白了，谢谢
