### ISSUE TITLE
Error on npm run build

### ISSUE THREAD

**Issue by chrisyao4700** [WecomTeam/InnerAppCodeSample#14]
Issue Summary
During a production build process, I encountered the following error message:

`Building for production...Error: error:0308010C:digital envelope routines::unsupported`

Steps to Reproduce
Clone the repository and install dependencies.
Run the build command with the production environment settings.
Expected Result
The build process should complete successfully without any errors.

Actual Result
The build process fails with the error:0308010C:digital envelope routines::unsupported error.

Environment
Operating System: [macOS]
Node.js version: [v17.9.1]
Build tool: `npm run build`
Additional Details
I have checked my OpenSSL installation and confirmed that I am using the latest version. I have also reviewed the documentation for the build tool and the repository, but have not found any relevant information to help resolve this issue.

Any assistance or guidance on how to resolve this issue would be greatly appreciated.

Thank you.

**Comment by meterscao** [comment]
This issue may be due to an unsupported version of NodeJS. I have found a few relevant results that may be helpful to you.

https://www.datainfinities.com/49/error-0308010C-digital-envelope-routines-unsupported
