### ISSUE TITLE
如何启动项目呢

### ISSUE THREAD

**Issue by timeIsMemory** [WecomTeam/InnerAppCodeSample#15]
我把项目克隆了下来,然后pnpm install,然后pnpm run serve和pnpm run start都不行,然后我删了node_modules,用yarn把依赖又装了一遍,结果还是报下面图片的问题
![报错](https://github.com/WecomTeam/InnerAppCodeSample/assets/131134473/c2537225-efad-48df-9d1b-244c405750aa)

**Comment by meterscao** [comment]
看起来是你 `vue-cli-service` 没有安装成功，应该是你本地没有 Vue 的完整环境，你试试重新安装下 `vue-cli-service`
